#!/bin/bash

LOCK_FILE="/tmp/multi_login_lock"

function is_locked() {
    [[ -e "$LOCK_FILE" ]]
}

function lock() {
    touch "$LOCK_FILE"
}

function unlock() {
    rm -f "$LOCK_FILE"
}

function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    isp=$(cat /etc/xray/isp)
    domain=$(cat /etc/xray/domain)
    status="$1"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN XRAY ⚠️</b>
<code>────────────────────</code>
<code>ISP    : ${isp}</code>
<code>Domain : ${domain}</code>
<code>────────────────────</code>
<code>Username        : ${user}</code>
<code>Limit IP        : ${iplimit}</code>
<code>Login IP Count  : ${cekcek}</code>
<code>────────────────────</code>
<code>Detail IP Login : </code>
$(echo -e "$ehh" | sed 's/^/<code>/;s/$/<\/code>/')
<code>────────────────────</code>
<code> ${status}</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function backup_and_remove_user() {
    exp=$1
    user=$2
    config_file=$3
    db_file=$4
    backup_file="/tmp/${user}_backup"

    # Backup the user configuration
    grep -w "^### $user $exp" $config_file > $backup_file
    grep -w "^### $user $exp" $db_file >> $backup_file

    # Remove the user configuration
    sed -i "/^### $user $exp/,/^},{/d" $config_file
    sed -i "/^### $user $exp/d" $db_file
}

function restore_user() {
    user=$1
    config_file=$2
    db_file=$3
    backup_file="/tmp/${user}_backup"

    # Restore the user configuration
    while read -r line; do
        echo "$line" >> $config_file
        echo "$line" >> $db_file
    done < $backup_file

    # Remove the backup file
    rm -f $backup_file
}

function process_user_protocol() {
    protocol=$1
    sudo rm /var/log/xray/access.log
    sudo rm -f /var/log/xray/access.log
    systemctl restart xray
    sleep 30
    rm -f /root/limit/*
    sleep 1
    data=$(grep -E "^#${protocol} " /etc/xray/config.json | cut -d ' ' -f 2)
    for user in $data
    do
        if [[ -f /etc/kyt/limit/${protocol}/ip/$user ]]; then
            nilai=$(cat /etc/kyt/limit/${protocol}/ip/$user)
            limitxray=$((nilai + 1))

            if [ ! -d "/root/limit/$user" ]; then
                mkdir -p /root/limit/$user
            fi

            cat /var/log/xray/access.log | grep $user | awk '{print $3}' | sed 's/tcp://g' | sed 's/:0//g' | sort | uniq > /root/limit/$user
            jumlahdata=$(wc -l < /root/limit/$user)
            if [ $jumlahdata -gt $limitxray ]; then
                kirimtele=" MULTI LOGIN DETECTED $user login $jumlahdata IP"
                echo "#${protocol} $kirimtele" >> /root/limit/rulesxray.txt
                BOT_TOKEN=$(sed -n '1p' /root/kyt/var.txt)
                ADMIN=$(sed -n '2p' /root/kyt/var.txt)
                curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d "chat_id=${ADMIN}" -d "text=${kirimtele}"
                exp=$(grep -E "^#${protocol} $user " /etc/xray/config.json | cut -d ' ' -f 3)
                backup_and_remove_user "$exp" "$user" "/etc/xray/config.json" "/etc/${protocol}/.${protocol}.db"
                systemctl restart xray
                send_log "Terkunci Selama 15 Menit"
                sleep 900
                restore_user "$user" "/etc/xray/config.json" "/etc/${protocol}/.${protocol}.db"
                systemctl restart xray
                send_log "Terunlock"
                rm -f /root/limit/*
                rm -f /root/limit/$user
            else
                echo "aman"
                rm -f /root/limit/*
            fi
        else
            echo "Limit IP file for user $user not found."
        fi
    done
}

function vmip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock
    process_user_protocol "vmess"
    unlock
}

function vlip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock
    process_user_protocol "vless"
    unlock
}

function trip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock
    process_user_protocol "trojan"
    unlock
}

if [[ ${1} == "vmip" ]]; then
    vmip
elif [[ ${1} == "vlip" ]]; then
    vlip
elif [[ ${1} == "trip" ]]; then
    trip
fi
