#!/bin/bash

LOCK_FILE="/tmp/multi_login_lock"
CHECK_INTERVAL=300  # Waktu cek ulang dalam detik (5 menit)
WAIT_TIME=300       # Waktu kunci dalam detik (5 menit untuk uji coba)

function is_locked() {
    [[ -e "$LOCK_FILE" ]]
}

function lock() {
    touch "$LOCK_FILE"
}

function unlock() {
    rm -f "$LOCK_FILE"
}

function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    isp=$(cat /etc/xray/isp)
    domain=$(cat /etc/xray/domain)
    status="$1"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN XRAY ⚠️</b>
<code>────────────────────</code>
<code>ISP    : ${isp}</code>
<code>Domain : ${domain}</code>
<code>────────────────────</code>
<code>Username        : ${user}</code>
<code>UUID            : ${uuid}</code>
<code>Limit IP        : ${iplimit}</code>
<code>Login IP Count  : ${cekcek}</code>
<code>────────────────────</code>
<code>Detail IP Login : </code>
$(echo -e "$ehh" | sed 's/^/<code>/;s/$/<\/code>/')
<code>────────────────────</code>
<code> ${status}</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function backup_and_remove_user() {
    exp=$1
    user=$2
    config_file=$3
    db_file=$4
    ip_limit_file=$5
    backup_dir="/tmp/${user}_backup"

    # Backup the user configuration
    mkdir -p $backup_dir
    cp $config_file $backup_dir/config.json
    cp $db_file $backup_dir/db.json
    echo $iplimit > $backup_dir/iplimit

    # Remove the user configuration
    sed -i "/^### $user $exp/,/^},{/d" $config_file
    sed -i "/^### $user $exp/d" $db_file
}

function restore_user() {
    user=$1
    config_file=$2
    db_file=$3
    ip_limit_dir=$4
    backup_dir="/tmp/${user}_backup"

    # Restore the user configuration from the backup directory
    cp $backup_dir/config.json $config_file
    cp $backup_dir/db.json $db_file
    cp $backup_dir/iplimit $ip_limit_dir/$user

    # Remove the backup directory
    rm -rf $backup_dir
}

function check_user() {
    protocol=$1
    config_file=$2
    db_file=$3
    ip_limit_dir="/etc/kyt/limit/$protocol/ip"

    data=( $(ls $ip_limit_dir) )
    for user in "${data[@]}"; do
        iplimit=$(cat "$ip_limit_dir/$user")
        ehh=$(grep "$user" /var/log/xray/access.log | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        cekcek=$(echo -e "$ehh" | wc -l)
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "$config_file" | cut -d ' ' -f 3 | sort | uniq)
            uuid=$(grep -A 1 "^### $user $exp" $config_file | grep 'id' | cut -d '"' -f 4)
            backup_and_remove_user "$exp" "$user" "$config_file" "$db_file" "$ip_limit_dir/$user"
            systemctl restart xray >> /dev/null 2>&1
            rm -rf "$ip_limit_dir/$user"
            send_log "Terkunci Selama 5 Menit"
            sleep $WAIT_TIME
            restore_user "$user" "$config_file" "$db_file" "$ip_limit_dir"
            systemctl restart xray >> /dev/null 2>&1
            send_log "Terunlock"
        fi
        sleep 0.1
    done
}

function vmip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock

    echo -n > /var/log/xray/access.log
    sleep 10
    check_user "vmess" "/etc/xray/config.json" "/etc/vmess/.vmess.db"

    unlock
}

function vlip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock

    echo -n > /var/log/xray/access.log
    sleep 10
    check_user "vless" "/etc/xray/config.json" "/etc/vless/.vless.db"

    unlock
}

function trip() {
    if is_locked; then
        echo "Another process is already running. Exiting..."
        exit 1
    fi
    lock

    echo -n > /var/log/xray/access.log
    sleep 10
    check_user "trojan" "/etc/xray/config.json" "/etc/trojan/.trojan.db"

    unlock
}

while true; do
    vmip
    vlip
    trip
    sleep $CHECK_INTERVAL
done
